name: 'medical_warehouse'
version: '1.0.0'
config-version: 2

profile: 'medical_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_warehouse:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging", "daily"]
    marts:
      +materialized: table
      +schema: analytics
      +tags: ["marts", "reporting"]
      dim_channels:
        +materialized: table
        +tags: ["dimension", "channel"]
      dim_dates:
        +materialized: table
        +tags: ["dimension", "date"]
      fct_messages:
        +materialized: incremental
        +unique_key: message_id
        +tags: ["fact", "messages"]

vars:
  raw_schema: "raw"
  staging_schema: "staging"
  analytics_schema: "analytics"