version: 2

sources:
  - name: raw
    description: "Raw Telegram data loaded from JSON files"
    schema: "{{ var('raw_schema', 'raw') }}"
    tables:
      - name: telegram_messages
        description: "Raw Telegram messages with all scraped fields"
        columns:
          - name: message_id
            description: "Unique message identifier from Telegram"
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: channel_title
            description: "Display title of the channel"
          - name: message_date
            description: "Timestamp when message was posted"
          - name: message_text
            description: "Text content of the message (product info, prices, etc.)"
          - name: has_media
            description: "Whether message contains media (image/video)"
          - name: image_path
            description: "Local path to downloaded image file"
          - name: views
            description: "Number of views on the message"
          - name: forwards
            description: "Number of times message was forwarded"
          - name: extracted_at
            description: "Timestamp when data was extracted"
          - name: raw_data
            description: "Original JSON data for debugging"

models:
  - name: stg_telegram_messages
    description: "Cleaned and standardized Telegram messages. This is the staging layer where we apply data quality rules and prepare data for analytics."
    
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - not_null
          - unique
          
      - name: channel_name
        description: "Channel identifier"
        tests:
          - not_null
          
      - name: message_date
        description: "Message posting timestamp"
        tests:
          - not_null
          
      - name: message_text
        description: "Cleaned message content"
        
      - name: views
        description: "Number of views (ensured non-negative)"
        
      - name: forwards
        description: "Number of forwards (ensured non-negative)"
        
      - name: message_length
        description: "Character count of message text"
        
      - name: has_image_flag
        description: "Boolean indicating if message has an image"
        
      - name: engagement_score
        description: "Calculated engagement metric (views + 5*forwards)"